plugins:
  theoreticalbot_enabled:
    default: true
    client: true
  theoreticalbot_username:
    type: username
    default: ''
    client: true
  theoreticalbot_categories:
    type: category_list
    default: ''
  theoreticalbot_send_first_post_replies:
    default: false
    client: true